# Original from envoyproject/envoy:examples/front-proxy/Dockerfile-frontenvoy
# Modified by DataDog:
# - add install step for dd-opentracing-cpp library
FROM envoyproxy/envoy:latest

ARG DATADOG_PLUGIN_VERSION=0.3.6

ADD https://github.com/DataDog/dd-opentracing-cpp/releases/download/v${DATADOG_PLUGIN_VERSION}/linux-amd64-libdd_opentracing_plugin.so.gz linux-amd64-libdd_opentracing_plugin.so.gz
RUN gunzip linux-amd64-libdd_opentracing_plugin.so.gz -c > /usr/local/lib/libdd_opentracing.so

CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
