version: 2

defaults: &defaults
  working_directory: ~/dd-opentracing-cpp
  docker:
    - image: datadog/docker-library:dd_opentracing_cpp_build_0_3_4

jobs:
  build:
    <<: *defaults
    environment:
      CMAKE_ARGS: -DBUILD_PLUGIN=ON -DBUILD_SHARED=OFF
      NGINX_OPENTRACING_VERSION: 0.7.0
      NGINX_VERSION: 1.14.0
    steps:
      - checkout
      - run:
          name: Run clang-format
          command: |
            find include src test -iname '*.h' -o -iname '*.cpp' | while read fname; do 
              changes=$(clang-format-5.0 -output-replacements-xml $fname | grep -c "<replacement " || true)
              if [ $changes != 0 ]
              then
                clang-format-5.0 -output-replacements-xml $fname
                echo "$fname did not pass clang-format, consider running: find include src test -iname '*.h' -o -iname '*.cpp' | xargs clang-format-5.0 -i"
                exit 1
              fi
            done
      - run:
          name: Build source dependencies
          command: |
            ./scripts/install_dependencies.sh
      - run:
          name: Build (with cmake)
          command: |
            rm -rf .build
            mkdir -p .build
            mkdir -p /tmp/build/
            cd .build
            cmake $CMAKE_ARGS ..
            make
            cp libdd_opentracing_plugin.so /tmp/build/libdd_opentracing_plugin.so
      - run:
          name: Build (with bazel)
          command: |
            export CC=clang-5.0
            export CXX=clang++-5.0
            bazel build //:dd_opentracing_cpp
      - run:
          name: Build opentracing-nginx
          command: |
            wget https://github.com/opentracing-contrib/nginx-opentracing/archive/v${NGINX_OPENTRACING_VERSION}.tar.gz -O nginx-opentracing.tar.gz
            mkdir nginx-opentracing
            tar zxvf nginx-opentracing.tar.gz -C nginx-opentracing --strip-components=1

            wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz -O nginx-${NGINX_VERSION}.tar.gz
            tar zxvf nginx-${NGINX_VERSION}.tar.gz
            # TODO(willgittoes-dd): Get these configure args automatically by installing nginx and using `nginx -V`.
            cd nginx-${NGINX_VERSION}
            ./configure \
              --prefix=/etc/nginx --modules-path=/usr/lib/nginx/modules \
              --user=nginx --group=nginx --with-compat --with-file-aio --with-threads \
              --with-cc-opt="-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-${NGINX_VERSION}/debian/debuild-base/nginx-${NGINX_VERSION}=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC" \
              --with-ld-opt='-Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' \
              --add-dynamic-module=../nginx-opentracing/opentracing
            make modules
            cp objs/ngx_http_opentracing_module.so /tmp/build/ngx_http_opentracing_module.so
      - persist_to_workspace:
          root: /tmp/
          paths:
            - build
      - store_artifacts:
          path: /tmp/build

  test_sanitizer_base: &test_sanitizer_base
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build source dependencies
          command: |
            ./scripts/install_dependencies.sh
      - run:
          name: Build and test
          command: |
            rm -rf .build
            mkdir -p .build
            cd .build
            cmake $CMAKE_ARGS ..
            make
            env $RUN_ARGS ctest --output-on-failure

  test_tsan:
    <<: *test_sanitizer_base
    environment:
      CMAKE_ARGS: -DBUILD_TESTING=ON -DSANITIZE_THREAD=On -DSANITIZE_UNDEFINED=On
      RUN_ARGS: TSAN_OPTIONS=detect_deadlocks=1:second_deadlock_stack=1

  test_asan:
    <<: *test_sanitizer_base
    environment:
      CMAKE_ARGS: -DBUILD_TESTING=ON -DSANITIZE_ADDRESS=On
      RUN ARGS:

  integration_test_nginx:
    working_directory: ~/dd-opentracing-cpp
    docker:
      - image: datadog/docker-library:dd_opentracing_cpp_test_0_3_0
    environment:
      NGINX_VERSION: 1.14.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install nginx
          command: |
            CODENAME=$(lsb_release -s -c) # eg "bionic", "xenial"
            wget http://nginx.org/keys/nginx_signing.key
            apt-key add nginx_signing.key
            echo deb http://nginx.org/packages/ubuntu/ ${CODENAME} nginx >> /etc/apt/sources.list
            echo deb-src http://nginx.org/packages/ubuntu/ ${CODENAME} nginx >> /etc/apt/sources.list
            apt-get update
            apt-get install nginx=${NGINX_VERSION}-1~${CODENAME}
      - run:
          name: Integration test
          command: |
            # Install the Datadog plugin
            NGINX_MODULES=$(nginx -V 2>&1 | grep "configure arguments" | sed -n 's/.*--modules-path=\([^ ]*\).*/\1/p')
            cp ./build/libdd_opentracing_plugin.so /usr/local/lib/libdd_opentracing_plugin.so
            cp ./build/ngx_http_opentracing_module.so ${NGINX_MODULES}/ngx_http_opentracing_module.so
            # Change the config to use it.
            cd ./test/integration/nginx/
            NGINX_CONF=$(nginx -V 2>&1 | grep "configure arguments" | sed -n 's/.*--conf-path=\([^ ]*\).*/\1/p')
            cp nginx.conf $NGINX_CONF
            cp dd-config.json /etc/dd-config.json
            mkdir -p /var/www/
            cp index.html /var/www/
            # Run the tests.
            ./nginx_integration_test.sh

_workflow_filters:
  _version_tag: &version_tag
    # Allows semver or "test" tags, with any suffix.
    # eg v1.2.3 v0.1.1 v1.2.3-ayy-lmao test test-ayy-lmao
    # "test" is useful if you want to ensure all workflows run without creating a version.
    only: /(v[0-9]+\.[0-9]+\.[0-9]|test).*/

  _run_on_release_tag: &run_on_release_tag
    filters:
      tags:
        <<: *version_tag

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          <<: *run_on_release_tag
      - test_tsan:
          <<: *run_on_release_tag
      - test_asan:
          <<: *run_on_release_tag
      - integration_test_nginx:
          <<: *run_on_release_tag
          requires:
            - build
