FROM nginx:1.17.3

RUN apt update && \
    apt -y install wget && \
    wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/v0.9.0/linux-amd64-nginx-1.17.3-ngx_http_module.so.tgz && \
    tar -C /etc/nginx/modules -xvf linux-amd64-nginx-1.17.3-ngx_http_module.so.tgz && \
    rm linux-amd64-nginx-1.17.3-ngx_http_module.so.tgz && \
    wget https://github.com/DataDog/dd-opentracing-cpp/releases/download/v1.1.2/linux-amd64-libdd_opentracing_plugin.so.gz && \
    gunzip linux-amd64-libdd_opentracing_plugin.so.gz && \
    mv linux-amd64-libdd_opentracing_plugin.so /usr/local/lib/libdd_opentracing_plugin.so
