version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./datadog-config.json:/etc/datadog-config.json
    ports:
      - "8080:8080"

  fastcgi-app:
    build:
      context: .
      dockerfile: ./Dockerfile.fastcgi-app
    environment:
      - DD_AGENT_HOST=dd-agent

  traced-backend:
    build:
      context: .
      dockerfile: ./Dockerfile.traced-backend
    environment:
      - DD_AGENT_HOST=dd-agent

  dd-agent:
    # image: 'datadog/agent'
    image: cgilmour/datadog-agent:hack
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOG_LEVEL=debug
